import { NextResponse } from 'next/server';
import { CreateLinkInput, createLinkSchema } from './validation';
import { validate } from '@/lib/validator';
import { prisma } from '@/lib/prisma';

const postHandler = async (req: Request & { body: CreateLinkInput }): Promise<Response> => {
	const { link } = req.body;
	// @ts-expect-error shortLinkCode will be generated by prisma extension
	const createdLink = await prisma.linkList.create({ data: { originalLink: link } });
	const { id, originalLink, views, shortLink } = createdLink;

	return NextResponse.json({
		success: true,
		data: { id, originalLink, views, shortLink },
	});
};

const getHandler = async (): Promise<Response> => {
	const links = await prisma.linkList.findMany({
		select: { id: true, originalLink: true, views: true, shortLink: true },
		orderBy: { id: 'desc' },
	});

	return NextResponse.json({
		success: true,
		data: { links },
	});
};

export const POST = validate(createLinkSchema)(postHandler);
export const GET = getHandler;
